#!/bin/bash

inc_vol() {
  pamixer -i 5
}

dec_vol() {
  pamixer -d 5
}

toggle_vol() {
  pamixer -t
}

if [[ "$1" == "--inc" ]]; then
  inc_vol
elif [[ "$1" == "--dec" ]]; then
  dec_vol
elif [[ "$1" == "--toggle-vol" ]]; then
  toggle_vol
fi
