#!/bin/bash

inc_volume() {
  pamixer -i 5
}

dec_volume() {
  pamixer -d 5
}

toggle_vol() {
  pamixer -t
}

inc_mic() {
  pamixer
}

if [[ "$1" == "--inc" ]]; then
  inc_volume
elif [[ "$1" == "--dec" ]]; then
  dec_volume
elif [[ "$1" == "--toggle-vol" ]]; then
  toggle_vol
fi
