theme {
  color_scheme = /home/grsh/.local/share/color-schemes/GraphiteDark.colors
  icon_theme = Papirus-Dark
  style = kvantum-dark
  font_fixed = JetBrains Mono
  font_fixed_size = 10
  font = Inter Medium
  font_size = 10
}
